# Test HTTP requests
### use with: REST Client extension

### GET all items
GET http://localhost:3000/items

### Add new item with id
POST http://localhost:3000/items
Content-Type: application/json

 {"name": "Mandariini"}

### Update item
PUT http://localhost:3000/items
Content-Type: application/json

 {"name": "Päivitetty Mandariini"}

### Delete item with id
DELETE http://localhost:3000/items/7
Content-Type: application/json 

 {"name": "Poistettu itemi"}